-- V1__create_tables.sql
-- Tüm temel tabloları oluşturur

-- === STUDENTS ===
CREATE TABLE students (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          student_number VARCHAR(50) NOT NULL UNIQUE,
                          first_name VARCHAR(50) NOT NULL,
                          last_name VARCHAR(50) NOT NULL,
                          email VARCHAR(100) NOT NULL UNIQUE,
                          date_of_birth DATE,
                          gender VARCHAR(20),
                          phone VARCHAR(20),
                          address TEXT,
                          enrollment_year INT,
                          department VARCHAR(100),
                          status VARCHAR(20) DEFAULT 'ACTIVE',
                          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                          updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_students_email ON students(email);
CREATE INDEX idx_students_student_number ON students(student_number);
CREATE INDEX idx_students_department ON students(department);

-- === TEACHERS ===
CREATE TABLE teachers (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          teacher_number VARCHAR(50) NOT NULL UNIQUE,
                          first_name VARCHAR(50) NOT NULL,
                          last_name VARCHAR(50) NOT NULL,
                          email VARCHAR(100) NOT NULL UNIQUE,
                          phone VARCHAR(20),
                          department VARCHAR(100),
                          title VARCHAR(50),
                          status VARCHAR(20) DEFAULT 'ACTIVE',
                          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                          updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_teachers_email ON teachers(email);
CREATE INDEX idx_teachers_department ON teachers(department);

-- === COURSES ===
CREATE TABLE courses (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         course_code VARCHAR(20) NOT NULL UNIQUE,
                         name VARCHAR(100) NOT NULL,
                         credit INT NOT NULL,
                         department VARCHAR(100),
                         start_date DATE NOT NULL,
                         end_date DATE NOT NULL,
                         created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                         updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_courses_department ON courses(department);
CREATE INDEX idx_courses_date_range ON courses(start_date, end_date);

-- === ENROLLMENTS ===
-- Öğrencilerin ders kayıtları
CREATE TABLE enrollments (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
                             course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
                             enrollment_date TIMESTAMP NOT NULL DEFAULT NOW(),
                             grade NUMERIC(2,1),
                             status VARCHAR(20) DEFAULT 'ENROLLED',
                             created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                             updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
                             UNIQUE(student_id, course_id)
);

CREATE INDEX idx_enrollments_student ON enrollments(student_id);
CREATE INDEX idx_enrollments_course ON enrollments(course_id);

-- === TEACHER_ASSIGNMENTS ===
CREATE TABLE teacher_assignments (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     teacher_id BIGINT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
                                     course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
                                     assigned_date TIMESTAMP NOT NULL DEFAULT NOW(),
                                     role VARCHAR(50) DEFAULT 'INSTRUCTOR',
                                     created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                                     updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
                                     UNIQUE(teacher_id, course_id)
);

CREATE INDEX idx_teacher_assignments_teacher ON teacher_assignments(teacher_id);
CREATE INDEX idx_teacher_assignments_course ON teacher_assignments(course_id);

-- === SYSTEM_LOGS ===
-- Sistem logları (işlemler, hata kayıtları, audit trail)
CREATE TABLE system_logs (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             log_level VARCHAR(20) NOT NULL,       -- INFO, WARN, ERROR
                             message TEXT NOT NULL,
                             logger VARCHAR(100),
                             thread VARCHAR(50),
                             created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_system_logs_level ON system_logs(log_level);
CREATE INDEX idx_system_logs_created_at ON system_logs(created_at);
